language: csharp

dotnet: 2.1.3

# dependencies (netcore)
# addons:
#   apt:
#     packages:
#        - libunwind8
#        - msbuild

before_install:
  # - msbuild /version
  - dotnet --version
  - dotnet --info
  # - chmod +x build.sh

# script:
#   - ./build.sh unittest
