jobs:

- job: Windows
  pool:
    vmImage: win1803
  # container: 'mcr.microsoft.com/dotnet/core/sdk:2.2.105-nanoserver-1803'
  steps:
  - powershell: |
      dotnet --version
      .\build.ps1
      if ($lastexitcode -ne 0){ exit $lastexitcode }

- job: Linux
  pool:
    vmImage: Ubuntu-16.04
  container: mcr.microsoft.com/dotnet/core/sdk:2.2.105
  steps:
  - script: |
      set -e
      ./build.sh
      ./build-checksum.sh
  - task: CopyFiles@2
    inputs:
      contents: bin/*.nupkg
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: nuget