pool:
  vmImage: Ubuntu-16.04
steps:
- script: |
    ./build.sh
    sha256sum bin/*.nupkg
- task: CopyFiles@2
  inputs:
    contents: bin/*.nupkg
    flattenFolders: true
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: copy nupkg files
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: packages
    artifactType: filePath