[<RequireQualifiedAccess>]
module Froto.TypeProvider.Runtime.ResizeArray

/// Adds item to the instance of ResizeArray casted to object.
/// Useful when argument of type ResizeArray<T> can't be passed directly (without casting)
/// when T - is a type generated by the type provider.
let add<'T> (list: obj) (item: 'T) =
    let list = list :?> ResizeArray<'T>
    list.Add item