name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
    - name: build, test, pack
      run: ./build.sh
    - name: push
      run: dotnet nuget push -s https://www.myget.org/F/froto/api/v2/package -k ${{ secrets.myget_froto_api_key }} bin/*.nupkg