name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      # with:
      #   dotnet-version: 3.0.100-preview8-013656
    # - uses: docker://mcr.microsoft.com/dotnet/core/sdk:2.2.105
    #   with:
    #     args: ./build.sh
    - run: |
        dotnet tool install -g nbgv --version 2.3.167
        nbgv get-version -v SemVer2
        # export VERSION=`nbgv get-version -v SemVer2`
        # ./build.sh