name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: look for dotnet
      run: dotnet --info
    - uses: docker://mcr.microsoft.com/dotnet/core/sdk:2.2.105
      with:
        args: ./build.sh